### ISSUE TITLE
Please release the reconstructed 3D meshes.

### ISSUE THREAD

**Issue by AlbertHuyb** [kyleleey/RICO#1]
Thanks for the great work and the open-source code!

Could you please release the reconstructed 3D meshes for objects in the scannet scenes and the synthetic scenes? 
In that case, it would be more convenient to follow your work and compare with RICO.

Thanks!

Best regards

**Comment by AlbertHuyb** [comment]
And it would be better if you could provide the scene_id list for ScanNet dataset.

Thanks!

**Comment by kyleleey** [comment]
Hi, I have just uploaded a version of my previous extracted meshes in this [link](https://drive.google.com/drive/folders/1fq6k56q7CU21KrAAJ9SUIQyhM2FvqmpT?usp=sharing).

These meshes are scaled and shifted back to original world coordinates. Remember that because the space for marching cube is set heuristically and it's rather large, for some objects and scenes, there are some floating structures in space which I removed them in the post-processing stage. However, these structures are **not connected** to the original meshes, which don't have effects on the paper's motivation and results. Like in our evaluation [script](https://github.com/kyleleey/RICO/blob/main/synthetic_eval/evaluate.py#L39) there also has this kind of processing.

I observed two possible reasons for these structures:
- The camera trajectory doesn't cover all the space in marching cube range, for example in my synthetic scenes, the camera actually never facing upward.
- The rendering formulation of NeuS has great possibility of causing this effect, on the other hand, VolSDF rendering formulation may causes a warping face.

**Comment by AlbertHuyb** [comment]
Thanks for your quick reply and the reconstructed meshes.

I noticed that you named these scenes with scan1, scan2, etc. Could you please list the original scene_id in the ScanNet dataset? For example, I think scan1 in your folder corresponds to scene0050_00.

Thanks.

Best regards.

**Comment by kyleleey** [comment]
Oh sorry I missed this part. The correspondence is as:
- scan1: scene0050_00
- scan2: scene0580_00
- scan3: scene0616_00
- scan4: scene0024_00
- scan5: scene0038_00
- scan6: scene0113_00
- scan7: scene0000_00

**Comment by AlbertHuyb** [comment]
Thanks a lot!

Best wishes

**Comment by jmoon0714** [comment]
Hello! Can you please release the reconstructed meshes for Replica as well, if you have them? Seems like one example is provided in the main paper. it'd be awesome if you could share the meshes for that and others in the dataset if you have them. Thank you!
