### ISSUE TITLE
How to get processed data from ScanNet raw data?

### ISSUE THREAD

**Issue by DaLi-Jack** [kyleleey/RICO#6]
Hi, Congrats for your great work!
I found you've already answered this in a similar issue #3 , but could you give me more details?
I also found the data processing method from another repo [vMAP](https://github.com/kxhit/vMAP/tree/master#dataset), but it is not exactly the same as the data you gave. 
The main difference is that vMAP has more objects, it looks like you removed some objects in ScanNet.
Could you give me more details about your data generation?
I would be grateful for any help you can provide!

**Comment by kyleleey** [comment]
Hi Junfeng,

That's true I didn't use all the available instances in one ScanNet scene according to their annotations. Because ScanNet's annotation is not that accurate and I think some instances are too detailed, but there is no doubt you can easily use RICO / Objsdf / or recent Objsdf++ on scenes with more instances.

In terms of my data generation, I didn't plan to open-source the script because it was a raw version. Basically I visualized all the instances from original ScanNet annotations, and then get the IDs I want to reconstruct, and generate new instance masks for each view.

The only detail here is when generating new instance masks(the desired objects keep their IDs, while all other pixels set as background ID 0), I need to also resize the original ScanNet's instance mask to current resolution, and here basically I resize the 0-1 binary mask for each object, set the resized mask to still contain only {0,1}, and fuse the masks for all instances together. For overlapping pixels I just randomly choose to keep one Instance ID. The purpose is to make the resized instance masks still only have the limited IDs.

**Comment by DaLi-Jack** [comment]
okk, I see! Thanks for your help!
